// Mocks generated by Mockito 5.4.0 from annotations
// in flight_tracker_app/test/features/flights/data/repositories/flights_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flight_tracker_app/core/network/network_info.dart' as _i5;
import 'package:flight_tracker_app/features/flights/data/data_sources/flights_remote_data_source.dart'
    as _i3;
import 'package:flight_tracker_app/features/flights/domain/entities/flights.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlights_0 extends _i1.SmartFake implements _i2.Flights {
  _FakeFlights_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlightsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlightsRemoteDataSource extends _i1.Mock
    implements _i3.FlightsRemoteDataSource {
  @override
  _i4.Future<_i2.Flights> getFlightsByNumber(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlightsByNumber,
          [number],
        ),
        returnValue: _i4.Future<_i2.Flights>.value(_FakeFlights_0(
          this,
          Invocation.method(
            #getFlightsByNumber,
            [number],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Flights>.value(_FakeFlights_0(
          this,
          Invocation.method(
            #getFlightsByNumber,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.Flights>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
