// Mocks generated by Mockito 5.4.0 from annotations
// in flight_tracker_app/test/features/flights/presentation/flights_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flight_tracker_app/core/error/failures.dart' as _i6;
import 'package:flight_tracker_app/core/utils/input_converter.dart' as _i8;
import 'package:flight_tracker_app/features/flights/domain/entities/flights.dart'
    as _i7;
import 'package:flight_tracker_app/features/flights/domain/repositories/flights_repository.dart'
    as _i2;
import 'package:flight_tracker_app/features/flights/domain/use_cases/get_flights_by_number.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlightsRepository_0 extends _i1.SmartFake
    implements _i2.FlightsRepository {
  _FakeFlightsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFlightsByNumber].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFlightsByNumber extends _i1.Mock
    implements _i4.GetFlightsByNumber {
  @override
  _i2.FlightsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFlightsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeFlightsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FlightsRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Flights>> call(_i4.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Flights>>.value(
            _FakeEither_1<_i6.Failure, _i7.Flights>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.Flights>>.value(
                _FakeEither_1<_i6.Failure, _i7.Flights>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Flights>>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i8.InputConverter {
  @override
  _i3.Either<_i6.Failure, int> stringToUnsignedInteger(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #stringToUnsignedInteger,
          [str],
        ),
        returnValue: _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
        returnValueForMissingStub: _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
      ) as _i3.Either<_i6.Failure, int>);
}
