// Mocks generated by Mockito 5.4.0 from annotations
// in flight_tracker_app/test/features/airports/presentation/airports_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flight_tracker_app/core/error/failures.dart' as _i6;
import 'package:flight_tracker_app/core/utils/input_converter.dart' as _i8;
import 'package:flight_tracker_app/features/airports/domain/entities/airport.dart'
    as _i7;
import 'package:flight_tracker_app/features/airports/domain/repositories/airports_repository.dart'
    as _i2;
import 'package:flight_tracker_app/features/airports/domain/use_cases/get_airports_by_country_code.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAirportsRepository_0 extends _i1.SmartFake
    implements _i2.AirportsRepository {
  _FakeAirportsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAirportsByCountryCode].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAirportsByCountryCode extends _i1.Mock
    implements _i4.GetAirportsByCountryCode {
  @override
  _i2.AirportsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAirportsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAirportsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AirportsRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Airport>>> call(
          _i4.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Airport>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Airport>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Airport>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Airport>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Airport>>>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i8.InputConverter {
  @override
  _i3.Either<_i6.Failure, int> stringToUnsignedInteger(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #stringToUnsignedInteger,
          [str],
        ),
        returnValue: _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
        returnValueForMissingStub: _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
      ) as _i3.Either<_i6.Failure, int>);
  @override
  _i3.Either<_i6.Failure, String> stringToCountryCode(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #stringToCountryCode,
          [str],
        ),
        returnValue: _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #stringToCountryCode,
            [str],
          ),
        ),
        returnValueForMissingStub: _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #stringToCountryCode,
            [str],
          ),
        ),
      ) as _i3.Either<_i6.Failure, String>);
}
